services:
  voicebot-app-front:
    build:
      context: ../../src/front
      dockerfile: ../../docker/voicebot-app-front/Dockerfile.dev
    container_name: voicebot-app-front
    volumes:
      - ../../src/front:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    # Environment variables are loaded from env_file in root docker-compose.yml
    stdin_open: true
    tty: true
