version: '3.8'

services:
  test-machine:
    build:
      context: ../..
      dockerfile: docker/test-machine/Dockerfile
    env_file:
      - ../../.env
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ../../tests:/app/tests:ro
      - ../../src:/app/src:ro