
services:
  riva-builder:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ../../.env
    container_name: riva-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
      - ${HOME}/.docker:/root/.docker   # share host creds with container
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
    stdin_open: true
    tty: true